import { StyleSheet } from 'react-native';
const C = { bg: '#f1f5f9', surface: '#fff', muted: '#64748b', text: '#0f172a', border: '#e2e8f0', primary: '#2563eb', success: '#16a34a', warning: '#d97706', danger: '#dc2626', chip: '#e0f2fe', surfaceMuted: '#f8fafc' };
export const colors = C;
export default StyleSheet.create({
  safe: { flex: 1, backgroundColor: C.bg },
  scroll: { padding: 16, paddingBottom: 40, gap: 14 },
  center: { alignItems: 'center', justifyContent: 'center', padding: 40 },
  heroCard: { borderRadius: 18, overflow: 'hidden' },
  heroGradient: { backgroundColor: '#0f172a', padding: 20, gap: 8 },
  heroBadge: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: 'rgba(255,255,255,0.12)', alignSelf: 'flex-start', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 20 },
  heroBadgeText: { color: 'rgba(255,255,255,0.8)', fontSize: 11, fontWeight: '600', letterSpacing: 0.3 },
  heroTitle: { color: '#fff', fontSize: 22, fontWeight: '900' },
  heroSub: { color: 'rgba(255,255,255,0.7)', fontSize: 13, lineHeight: 19 },
  heroInfoRow: { flexDirection: 'row', gap: 8, marginTop: 4, flexWrap: 'wrap' },
  heroInfoBox: { backgroundColor: 'rgba(255,255,255,0.1)', borderRadius: 12, paddingHorizontal: 12, paddingVertical: 8, borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)' },
  heroInfoLabel: { color: 'rgba(255,255,255,0.6)', fontSize: 10, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.4 },
  heroInfoValue: { color: '#fff', fontSize: 13, fontWeight: '700', marginTop: 2 },
  card: { backgroundColor: C.surface, borderRadius: 16, borderWidth: 1, borderColor: C.border, padding: 16, gap: 10, shadowColor: '#0f172a', shadowOpacity: 0.06, shadowRadius: 8, shadowOffset: { width: 0, height: 3 }, elevation: 2 },
  cardTitle: { fontSize: 15, fontWeight: '800', color: C.text },
  cardSub: { fontSize: 12, color: C.muted, lineHeight: 17 },
  row: { flexDirection: 'row', alignItems: 'center' },
  spaceBetween: { justifyContent: 'space-between' },
  gap8: { gap: 8 },
  gap12: { gap: 12 },
  statsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  statCard: { width: '47%', borderRadius: 14, padding: 14, gap: 4, borderWidth: 1, borderColor: C.border, backgroundColor: C.surface },
  statLabel: { fontSize: 11, fontWeight: '600', color: C.muted, textTransform: 'uppercase', letterSpacing: 0.3 },
  statValue: { fontSize: 22, fontWeight: '900', color: C.text },
  statHelper: { fontSize: 11, color: C.muted },
  statIcon: { width: 36, height: 36, borderRadius: 10, alignItems: 'center', justifyContent: 'center', position: 'absolute', top: 12, right: 12 },
  emptyIcon: { width: 56, height: 56, borderRadius: 16, backgroundColor: C.surfaceMuted, alignItems: 'center', justifyContent: 'center', marginBottom: 12 },
  emptyTitle: { fontSize: 17, fontWeight: '800', color: C.text, textAlign: 'center' },
  emptyText: { fontSize: 13, color: C.muted, textAlign: 'center', lineHeight: 19, marginTop: 6 },
  // Hour grid
  hourGrid: { gap: 6 },
  hourRow: { flexDirection: 'row', alignItems: 'center', borderRadius: 12, padding: 12, gap: 10, borderWidth: 1, borderColor: C.border, backgroundColor: C.surface },
  hourRowLocked: { backgroundColor: '#fffbeb', borderColor: '#fde68a' },
  hourRowActive: { backgroundColor: '#eff6ff', borderColor: '#93c5fd' },
  hourLabel: { fontSize: 14, fontWeight: '700', color: C.text, width: 52 },
  hourBarWrap: { flex: 1, height: 22, borderRadius: 6, backgroundColor: C.surfaceMuted, overflow: 'hidden' },
  hourBarPlanned: { position: 'absolute', height: '100%', backgroundColor: 'rgba(15,23,42,0.12)', borderRadius: 6 },
  hourBarActual: { position: 'absolute', height: '100%', backgroundColor: C.primary, borderRadius: 6 },
  hourQty: { fontSize: 13, fontWeight: '700', color: C.text, width: 40, textAlign: 'right' },
  hourAction: { width: 36, height: 36, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
  hourActionOpen: { backgroundColor: C.primary },
  hourActionLocked: { backgroundColor: '#fef3c7' },
  // Modal
  modalOverlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(15,23,42,0.5)' },
  modalBackdrop: { flex: 1 },
  modalSheet: { backgroundColor: C.surface, borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 20, paddingBottom: 32, maxHeight: '80%', gap: 14 },
  modalHandle: { width: 40, height: 4, borderRadius: 2, backgroundColor: C.border, alignSelf: 'center' },
  modalTitle: { fontSize: 18, fontWeight: '900', color: C.text },
  modalSub: { fontSize: 13, color: C.muted },
  modalMiniStats: { flexDirection: 'row', gap: 8 },
  modalMiniStat: { flex: 1, borderRadius: 12, backgroundColor: C.surfaceMuted, padding: 10, gap: 2 },
  modalMiniLabel: { fontSize: 10, fontWeight: '600', color: C.muted, textTransform: 'uppercase' },
  modalMiniValue: { fontSize: 15, fontWeight: '800', color: C.text },
  empCard: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderRadius: 12, borderWidth: 1, borderColor: C.border, backgroundColor: C.surface, padding: 12, gap: 10 },
  empCardFocused: { borderColor: '#93c5fd', backgroundColor: '#eff6ff' },
  empName: { fontSize: 14, fontWeight: '700', color: C.text },
  empId: { fontSize: 11, color: C.muted },
  qtyInput: { width: 80, height: 40, borderRadius: 10, borderWidth: 1, borderColor: C.border, backgroundColor: C.surface, paddingHorizontal: 10, fontSize: 14, fontWeight: '600', color: C.text, textAlign: 'center' },
  qtyInputDisabled: { backgroundColor: C.surfaceMuted, color: C.muted },
  modalFooter: { flexDirection: 'row', gap: 10, marginTop: 4 },
  btnPrimary: { flex: 1, height: 48, borderRadius: 12, backgroundColor: '#0f172a', alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8 },
  btnSecondary: { flex: 1, height: 48, borderRadius: 12, backgroundColor: C.surface, borderWidth: 1, borderColor: C.border, alignItems: 'center', justifyContent: 'center' },
  btnPrimaryText: { color: '#fff', fontSize: 14, fontWeight: '700' },
  btnSecondaryText: { color: C.text, fontSize: 14, fontWeight: '600' },
  btnDisabled: { opacity: 0.5 },
  errorBox: { borderRadius: 12, backgroundColor: '#fef2f2', borderWidth: 1, borderColor: '#fecaca', padding: 12 },
  errorText: { color: '#b91c1c', fontSize: 13 },
  toast: { position: 'absolute', bottom: 24, left: 16, right: 16, backgroundColor: '#065f46', borderRadius: 14, padding: 14, flexDirection: 'row', alignItems: 'center', gap: 8, zIndex: 100, shadowColor: '#000', shadowOpacity: 0.2, shadowRadius: 12, elevation: 6 },
  toastText: { color: '#fff', fontSize: 13, fontWeight: '600', flex: 1 },
  pickerLabel: { fontSize: 12, fontWeight: '700', color: C.text, textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 4 },
});
